services:
  db:
    image: mariadb:11.1
    container_name: zeze-db
    restart: unless-stopped
    # env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: zeze_bizou
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpsecret
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql

  php:
    build: .
    container_name: zeze-php
    restart: unless-stopped
    working_dir: /var/www/wordpress
    volumes:
      - ./public:/var/www/wordpress
      - ./:/var/www
    # command: bash -c "composer install --no-dev --optimize-autoloader && php-fpm"

  web:
    image: nginx:alpine
    container_name: zeze-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/wordpress:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  whodb:
    image: clidey/whodb
    ports:
      - "8080:8080"

volumes:
  db_data:
