services:
  db:
    image: mariadb:11.1
    container_name: zeze-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zeze_bizou
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql

  php:
    build: .
    container_name: zeze-php
    restart: unless-stopped
    working_dir: /var/www/public/wordpress
    volumes:
      - ./public:/var/www/public/wordpress
      - ./.env/:/var/www/public/wordpress/.env
    expose:
      - "9000"
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: zeze-nginx
    restart: unless-stopped
    # ports:
    #   - "80:80"
    volumes:
      - ./public:/var/www/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wp.rule=PathPrefix(`/`)"
      - "traefik.http.routers.wp.entrypoints=web"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: zeze-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db           # nom du service MariaDB
      PMA_USER: db           # user par défaut (optionnel)
      PMA_PASSWORD: db       # password par défaut (optionnel)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=PathPrefix(`/phpmyadmin`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      # Pour futur SSL :
      #- "traefik.http.routers.phpmyadmin.entrypoints=websecure"
      #- "traefik.http.routers.phpmyadmin.tls=true"
    # ports:
    #   - "8080:80"            # accessible sur http://VPS:8080
    depends_on:
      - db

  traefik:
    image: traefik:v3.6
    container_name: zeze-traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "traefik.http.routers.wp.rule=PathPrefix(`/`)" # Provisoire en attendant le domaine
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080" # dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db_data:
