server {
    listen 80;
    server_name _;

    root /var/www/wordpress/wordpress;

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/wordpress/wordpress$fastcgi_script_name;
    }
}
