name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Build assets
        run: npm install && npm run build
        env:
          WP_DEFAULT_THEME: ${{ secrets.WP_DEFAULT_THEME }}

      - name: Deploy to VPS
        run: |
          rsync -avz --delete ./ deploy@135.181.103.94:/var/www/zeze-bizou
